--- 
  
#file to get new web servers up and running

  - name: get webservers up and running
    hosts: webservers
    become: true
    tasks:
    
# uninstall apache (you dont need this to run)

    - name: unistall apache httpd  (state=present is optional)
      apt:
        name: apache2
        state: absent
    
# install the docker.io container with apt

    - name: docker.io
      apt:
        update_cache: yes
        name: docker.io
        state: present
    
# install pythons pip installer with apt

    - name: Install pip3
      apt:
        name: python3-pip
        state: present
    
# install Docker module with pip

    - name: Install Python Docker Module
      pip:
        name: docker
        state: present
    
# launch the web container
 
    - name: download and lauch a docker web container
      docker_container:
        name: dvwa
        image: cyberxsecurity/dvwa
        state: started
        restart_policy: always
        published_ports: 80:80
    
# enable the docker service to run on start up
 
    - name: Enable Docker Service
      systemd:
        name: docker
        enabled: yes	
